"""
PyAgent 浏览器自动化模块

基于 Playwright 实现的浏览器自动化功能，支持：
- 浏览器控制（启动、关闭、导航等）
- DOM序列化（元素提取、文本提取等）
- 动作执行（点击、输入、滚动等）
- 多标签页管理
- 事件系统（事件类型定义和事件处理）
- CDP 会话管理（Chrome DevTools Protocol）
"""

from .actions import ActionExecutor, ActionResult
from .cdp_session import (
    CDPCommandResult,
    CDPCommands,
    CDPSessionInfo,
    CDPSessionManager,
    CDPSessionWrapper,
    SessionState,
)
from .controller import BrowserController, BrowserSession
from .dom_serializer import DOMElement, DOMSerializer
from .event_bus import (
    BaseEvent,
    BrowserEvent,
    BrowserStartEvent,
    BrowserStopEvent,
    ErrorEvent,
    EventBus,
    EventHandler,
    EventPriority,
    EventResult,
    EventState,
    FileDownloadedEvent,
    NavigateEvent,
    PageLoadedEvent,
    ScreenshotEvent,
    ScriptExecutedEvent,
    TabClosedEvent,
    TabCreatedEvent,
    TabSwitchedEvent,
    get_event_bus,
    set_event_bus,
)
from .events import (
    BrowserEvent as BrowserActionEvent,
    ClickCoordinateEvent,
    ClickElementEvent,
    CloseTabEvent,
    EventStatus,
    EventType,
    ExecuteScriptEvent,
    ExtractContentEvent,
    GetDropdownOptionsEvent,
    GoBackEvent,
    GoForwardEvent,
    NavigateToUrlEvent,
    NewTabEvent,
    RefreshEvent,
    ScreenshotEvent as ScreenshotActionEvent,
    ScrollEvent,
    SelectDropdownOptionEvent,
    SendKeysEvent,
    SwitchTabEvent,
    TypeTextEvent,
    UploadFileEvent,
    create_event,
)
from .tab_manager import TabInfo, TabManager
from .state import (
    BrowserState,
    BrowserStateHistory,
    DOMElement as StateDOMElement,
    DOMState,
    PageLoadState,
    StateDiff,
    StateManager,
    TabState,
)
from .registry import (
    ActionModel,
    ActionResult as RegistryActionResult,
    Controller,
    Registry,
    RegisteredAction,
    Tools,
)
from .locator import (
    ClickElementParams,
    ElementInfo,
    ElementLocator,
    InputTextParams,
    LocateResult,
    LocatorType,
)
from .loop_detector import (
    ActionRecord,
    LoopAlert,
    LoopDetector,
    LoopDetectorConfig,
    LoopType,
    PageFingerprint,
)
from .agent import (
    AgentHistory,
    AgentState,
    AgentStatus,
    BrowserAgent,
    MessageManager,
    StepResult,
)
from .planner import (
    Plan,
    PlanStatus,
    PlanStep,
    StepStatus,
    TaskPlanner,
)
from .vision import (
    BoundingBox,
    ScreenshotResult,
    VisionAnalysisResult,
    VisionMode,
    VisionProcessor,
)
from .structured_output import (
    ExtractedItem,
    ExtractionResult,
    StructuredOutputProcessor,
)
from .sensitive import (
    SensitiveDataConfig,
    SensitiveDataHandler,
    SensitiveDataHandler as SensitiveHandler,
    SensitiveDataType,
    SensitiveField,
    SensitiveLogFilter,
)
from .dom_enhanced import (
    DOMElementEnhanced,
    EnhancedDOMSerializer,
)
from .browser_tools import (
    BrowserTools,
    create_browser_tools,
)

__all__ = [
    "BrowserController",
    "BrowserSession",
    "DOMSerializer",
    "DOMElement",
    "DOMElementEnhanced",
    "EnhancedDOMSerializer",
    "ActionExecutor",
    "ActionResult",
    "TabManager",
    "TabInfo",
    "EventBus",
    "BaseEvent",
    "EventHandler",
    "EventResult",
    "EventPriority",
    "EventState",
    "BrowserEvent",
    "BrowserStartEvent",
    "BrowserStopEvent",
    "NavigateEvent",
    "PageLoadedEvent",
    "ScreenshotEvent",
    "ScriptExecutedEvent",
    "TabCreatedEvent",
    "TabClosedEvent",
    "TabSwitchedEvent",
    "FileDownloadedEvent",
    "ErrorEvent",
    "get_event_bus",
    "set_event_bus",
    "BrowserActionEvent",
    "EventType",
    "EventStatus",
    "NavigateToUrlEvent",
    "GoBackEvent",
    "GoForwardEvent",
    "RefreshEvent",
    "ClickElementEvent",
    "ClickCoordinateEvent",
    "TypeTextEvent",
    "ScrollEvent",
    "SendKeysEvent",
    "SwitchTabEvent",
    "CloseTabEvent",
    "NewTabEvent",
    "SelectDropdownOptionEvent",
    "GetDropdownOptionsEvent",
    "UploadFileEvent",
    "ScreenshotActionEvent",
    "ExecuteScriptEvent",
    "ExtractContentEvent",
    "create_event",
    "BrowserState",
    "BrowserStateHistory",
    "StateDOMElement",
    "DOMState",
    "PageLoadState",
    "StateDiff",
    "StateManager",
    "TabState",
    "CDPSessionManager",
    "CDPSessionWrapper",
    "CDPSessionInfo",
    "CDPCommandResult",
    "CDPCommands",
    "SessionState",
    "Registry",
    "RegisteredAction",
    "ActionModel",
    "RegistryActionResult",
    "Controller",
    "Tools",
    "ElementLocator",
    "ElementInfo",
    "LocateResult",
    "LocatorType",
    "ClickElementParams",
    "InputTextParams",
    "LoopDetector",
    "LoopDetectorConfig",
    "LoopAlert",
    "LoopType",
    "ActionRecord",
    "PageFingerprint",
    "BrowserAgent",
    "AgentState",
    "AgentStatus",
    "AgentHistory",
    "MessageManager",
    "StepResult",
    "TaskPlanner",
    "Plan",
    "PlanStatus",
    "PlanStep",
    "StepStatus",
    "VisionProcessor",
    "VisionMode",
    "ScreenshotResult",
    "VisionAnalysisResult",
    "BoundingBox",
    "StructuredOutputProcessor",
    "ExtractionResult",
    "ExtractedItem",
    "SensitiveDataHandler",
    "SensitiveHandler",
    "SensitiveDataConfig",
    "SensitiveDataType",
    "SensitiveField",
    "SensitiveLogFilter",
    "DOMElementEnhanced",
    "EnhancedDOMSerializer",
    "BrowserTools",
    "create_browser_tools",
]

__version__ = "0.8.2"
